version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3030:80'
    depends_on:
      - api
  graphql:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4050:4050'
    volumes:
      - /app/node_modules
      - .:/usr/src/app
    command: ["npm", "run", "graphql:dev"]
  kue:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3050:3050'
    volumes:
      - /app/node_modules
      - .:/usr/src/app
    command: ["npm", "run", "kue"]     
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    depends_on:
      - graphql    
      - kue  
