version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3030:80'
    depends_on:
      - api
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
    - "4466:4466"  
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: >-
              ${MONGO_DB} 
  kue:
    build: 
      context: .
      dockerfile: ./src/utils/jobQueue/queues/kue/Dockerfile.dev
    ports:
      - '3050:3050'
    volumes:
      - /app/node_modules
      - .:/usr/src/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    depends_on:
      - prisma
      - kue
